### PR TITLE
Added player.shuffle() function

### PR DESCRIPTION
**Pull request by NotJag**

### CODE REVIEW

**Review by 1Lucas1apk — COMMENTED** [review]
Remove track from queue already exists player.queue.remove(position)

**Comment by NotJag** [comment]
Just checking, queue.shuffle doesn't exist right?

**Comment by 1Lucas1apk** [comment]
> Just checking, queue.shuffle doesn't exist right?

Queue shuffle does not exist, but remove track does

**Comment by NotJag** [comment]
Removed my queue.remove(), should be good for merge now 👍

**Pull request merged**
